services:
  neo4j:
    image: neo4j:5.24.2-community
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"    # HTTP (Browser)
      - "7687:7687"    # Bolt (cuidado: veja segurança abaixo)
    env_file:
      - .env           # SOMENTE NEO4J_AUTH aqui
    environment:
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'  # bloom não é necessário na VPS
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_server_directories_import: /imports
      NEO4J_server_directories_logs: /logs
      NEO4J_server_memory_pagecache_size: 512M
      NEO4J_server_jvm_additional: "-Xms1G -Xmx1G"
    volumes:
      - ../neo4j/data:/data
      - ../neo4j/logs:/logs
      - ../neo4j/plugins:/plugins
      - ../data:/imports
      - ../exports:/exports

  neovis:
    build:
      context: ../web
      dockerfile: Dockerfile
    container_name: neovis
    restart: unless-stopped
    ports:
      - "8080:80"      # app web em http://<VPS>:8080
    depends_on:
      - neo4j

  # opcional: dashboards prontos
  neodash:
    image: neo4jlabs/neodash:2.3.4
    container_name: neodash
    restart: unless-stopped
    ports:
      - "5005:5005"
