# Projeto_Grafo_TCC/web/Dockerfile
FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
# se tiver outros assets (css/js), copie a pasta inteira:
# COPY . /usr/share/nginx/html
EXPOSE 80
